### ISSUE TITLE
Use ConfigureAwait(false) for all awaits

### ISSUE THREAD

**Issue by DSaunders** [tmenier/AsyncPoco#59]
To avoid deadlocks when forced to block on async code (for example, when migrating from a mostly synchronous codebase to `async`/`await`), and for performance reasons, it would be helpful to add `ConfigureAwait(false)` wherever `await` is used ([Async/Await - Best Practices in Asynchronous Programming](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx)).

Was it a deliberate decision not to use `ConfigureAwait(false)`, or would you be open to a PR adding this to all async calls?

**Comment by tmenier** [comment]
No, it wasn't deliberate. I would accept a PR.

I still would never recommend using AsyncPoco unless _all_ calls are made synchronously (stick with PetaPoco or something else in that case). Also note that if you're using ASP.NET Core, `ConfigureAwait` doesn't matter because there is no `SynchronizationContext`. That said, no argument that it's still considered a best practice for libraries.

**Comment by tmenier** [comment]
Sorry for the delay. Looks good to me, I'll get it released. Thans!

**Comment by tmenier** [comment]
This has been released and published to NuGet in 2.0.2

**Comment by DSaunders** [comment]
Thank you! 👍
